#import "../../lib.typ":*

== Bases and Dimension

We saw in the previous section that if $S$ is a generating set for a subspace $W$ and no proper subset of $S$ is a generating set for $W$, then $S$ must be linearly independent. A linearly independent generating set for $W$ possesses a very useful property: every vector in $W$ can be expressed in one and only one way as a linear combination of the vectors in the set.

#definition(title: "Basis")[
  A *basis* $beta$ for a vector space $V$ is a linearly independent subset of $V$ that generates $V$. If $beta$ is a basis for $V$, we also say that the vectors of $beta$ form a basis for $V$.
]

#example[
  Recalling that $"span"(emptyset) = {0}$ and $emptyset$ is linearly independent, we see that $emptyset$ is a basis for the zero vector space.
]

#example[
  In $KK^n$, let $e_1 = (1,0,0,dots,0), e_2 = (0,1,0,dots,0), dots, e_n = (0,0,dots,0,1)$; ${e_1, e_2, dots, e_n}$ is readily seen to be a basis for $KK^n$ and is called the *standard basis* for $KK^n$.
]

#example[
  In $M_(m times n)(KK)$, let $E^(i j)$ denote the matrix whose only nonzero entry is a 1 in the #emph("i")th row and #emph("j")th column. Then ${E^(i j) : 1 <= i <= m, 1 <= j <= n}$ is a basis for $M_(m times n)(KK)$.
]

#example[
  In $P_(n)(KK)$ the set ${1,x,x^2,dots, x^n}$ is a basis. We call this basis the *standard basis* for $P_(n)(KK)$.
]

#example[
  In $P(KK)$ the set ${1,x,x^2,dots}$ is a basis.
]

#important-box[
  Observe that the last example shows that a basis need not to be finite. Hence not every vector space has a finite basis.
]

The next theorem establishes the most significant property of a basis.

#theorem[
  Let $V$ be a vector space and $beta = {u_1, u_2, dots, u_n} subset.eq V$. Then $beta$ is a basis for $V$ *if and only if* each $v in V$ can be uniquely expressed as a linear combination of vectors of $beta$, that is, can be expressed in the form 
  $ v = lambda_1 u_1 + lambda_2 u_2 + dots.c + lambda_n u_n $
  for *unique* scalars $lambda_i in KK$.
] <thm:basis-thm>

If @thm:basis-thm holds, $v$ determines a *unique* _n_-tuple of scalars $(lambda_1, lambda_2, dots, lambda_n)$ and, conversely, each _n_-tuple of scalars determines a *unique* vector $v in V$ using the entries of the tuple as the coefficients of a linear combination of those vectors.

We are primarily interested in vector spaces having finite bases. The next theorem identifies a large class of vector spaces of this type.

#theorem[
  If a vector space $V$ is generated by a finite set $S$, then some subset of $S$ is a basis for $V$. Hence $V$ has a finite basis.
] <thm:finite-span-set>

Because of the method by which a basis $beta$ is obtained in the proof of @thm:finite-span-set (which is omitted), this theorem is often remembered as saying that a _finite spanning set for $V$ can be reduced to a basis for $V$_

The corollaries of the following theorem are perhaps the most significant result of this chapter.

#theorem(title: "Replacement Theorem")[
  Let $V$ be a vector space that is generated by a set $G$ containing exactly $n$ vectors, and let $L$ be a linearly independent subset of $V$ containing exactly $m$ vectors. Then $m <= n$ and there exists a $H subset.eq G$ containing exactly $n - m$ vectors such that $L union H$ generates $V$.
] <thm:replacement-thm>

#corollary[
  Let $V$ be a vector space having a finite basis. Then every basis for $V$ contains the same number of vectors.
] <cor:same-num-vectors>

If a vector space has a finite basis, @cor:same-num-vectors asserts that the number of vectors in _any_ basis for $V$ is an intrinsic property of $V$. This fact makes possible the following definitions.

#definition(title: "Dimension")[
  A vector space is called *finite-dimensional* if it has a basis consisting of a finite number of vectors. The unique number of vectors in each basis for $V$ is called the *dimension* of $V$ and is denoted by $"dim"(V)$. A vector space that is not finite-dimensional is called *infinite-dimensional*.
]

The following results are consequences of the examples given at the beginning of this section.

#example[
  The vector space ${0}$ has dimension zero.
]

#example[
  The vector space $KK^n$ has dimension $n$.
]

#example[
  The vector space $M_(m times n)(KK)$ has dimension $m n$.
]

#example[
  The vector space $P_(n)(KK)$ has dimension $n + 1$.
]

The following examples show that the dimension of a vector space depends on its field of scalars.

#example[
  Over the field of complex numbers, the vector space of complex numbers has dimension 1. (A basis is ${1}$)
]

#example[
  Over the field of real numbers, the vector space of complex numbers has dimension 2. (A basis is ${1, i}$)
]

Just as no linearly independent subset of a finite-dimensional vector space $V$ can contain more than $"dim"(V)$ vectors, a corresponding statement can be made about the size of a generating set.

#corollary[
  Let $V$ be a vector space with dimension $n$.
  - Any finite generating set for $V$ contains at least $n$ vectors, and a generating set for $V$ that contains exactly $n$ vectors is a basis for $V$.
  - Any linearly independent subset of $V$ that contains exactly $n$ vectors is a basis for $V$.
  - Every linearly independent subset of $V$ can be extended to a basis for $V$.
]

#example[
  $ {x^2 + 3x - 2, 2x^2 + 5x - 3, -x^2 -4x + 4}$ is a basis for $P_(2)(RR) $
]

#example[
  $ {
    mat(1,1;1,0), mat(1,1;0,1),mat(1,0;1,1),mat(0,1;1,1)
  } $
  is a basis for $M_(2 times 2)(RR)$.
]

#example[
  $ {(1,0,0,-1),(0,1,0,-1),(0,0,1,-1),(0,0,0,1)}$ is a basis for $RR^4 $.
]

#tip-box[
  Let's say we need to prove that $<beta> = V$, where $V$ is a vector space and $beta subset.eq V$. We only need to prove $ V subset.eq <beta>$, since $<beta> subset.eq V$ always holds.
]

=== An Overview of Dimension and Its Consequences

@thm:finite-span-set as well as @thm:replacement-thm (the replacement theorem) and its corollaries contain a wealth of information about the relationship among linearly independent sets, bases, and generating sets. The next is a summary about the results of this section.

A *basis* for a vector space $V$ is a *linearly independent subset* of $V$ that *generates* $V$. If $V$ has a *finite basis*, then *every* basis for $V$ contains the *same number* of vectors. This number is called the *dimension* of $V$, and $V$ is said to be *finite-dimensional*. Thus if the dimension of $V$ is $n$, every basis for $V$ contains *exactly* $n$ vectors. Moreover, *every linearly independent subset* of $V$ contains *no more* than $n$ vectors and *can be extended to a basis* for $V$ by *including appropriately* chosen vectors. Also, each generating set for $V$ contains *at least* $n$ vectors and *can be reduced to a basis* for $V$ by *excluding appropriately* chosen vectors.

// TODO: ADD the image for the preceding summary

=== The Dimension of Subspaces

The next theorem relates the dimension of a subspace to the dimension of the vector space that contains it.

#theorem[
  Let $W$ be a subspace of a finite-dimensional vector space $V$. Then $W$ is finite-dimensional and $"dim"(W) <= "dim"(V)$. Moreover, if $"dim"(W) = "dim"(V)$, then $W = V$.
]

#example[
  Let $ W = {(a_1, a_2, a_3, a_4, a_5) in KK^5 : a_1 + a_3 + a_5 = 0, a_2 = a_4} $
  It is easily shown that $W$ is a subspace of $KK^5$ having
  $ {(-1,0,1,0,0),(-1,0,0,0,1),(0,1,0,1,0)} $ as a basis. Thus $"dim"(W) = 3$.
]

#example[
  The set of diagonal $n times n$ matrices is a subspace $W$ of $M_(n times n)(KK)$. A basis for $W$ is
  $ {E^(11), E^(22),dots, E^(n n)}, $
  where $E^(i j)$ is the matrix in which the only nonzero entry is a 1 in the #emph("i")th row and #emph("j")th column. Thus $"dim"(W) = n$.
]

#example[
  We saw that the set of symmetric $n times n$ matrices is a subspace $W$ of $M_(n times n)$(KK). A basis for $W$ is $ A^(i j) : 1 <= i <= j <= n $
  where $A^(i j)$ is the $n times n$ matrix having 1 in the #emph("i")th row and #emph("j")th column, 1 in the #emph("j")th row and #emph("i")th column, and 0 elsewhere. It follows that
  $ "dim"(W) = n + (n - 1) + dots + 1 = 1/2 n (n + 1)$.
]

#corollary[
  If $W$ is a subspace of a finite-dimensional vector space $V$, then any basis for $W$ can be extended to a basis for $V$.
]

// TODO: The Lagrange Interpolation Formula
// TODO: Maximal Linearly Independent Subsets

